# Generated by Django 2.1.5 on 2019-01-06 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleGame',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name_player_1', models.CharField(max_length=32)),
                ('name_player_2', models.CharField(max_length=32)),
                ('move_player_1', models.CharField(max_length=1)),
                ('move_player_2', models.CharField(max_length=1)),
                ('winner', models.CharField(max_length=32)),
            ],
        ),
    ]
