# Generated by Django 2.1.5 on 2019-01-06 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190106_2055'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoundsDB',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name_player_1', models.CharField(max_length=32)),
                ('name_player_2', models.CharField(max_length=32)),
                ('move_player_1', models.CharField(max_length=1)),
                ('move_player_2', models.CharField(max_length=1)),
                ('winner', models.CharField(max_length=32, null=True)),
                ('round_1', models.CharField(max_length=32, null=True)),
                ('round_2', models.CharField(max_length=32, null=True)),
                ('round_3', models.CharField(max_length=32, null=True)),
            ],
        ),
    ]
