# Generated by Django 2.1.5 on 2019-01-06 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_roundsdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamersdb',
            name='id_game',
            field=models.IntegerField(auto_created=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamersdb',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
