# Generated by Django 2.1.5 on 2019-01-07 00:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20190106_2343'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamersdb',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
